name: Go

on:
  push:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: CGO_ENABLE=0 GOOS=windows go build -v -o lin.exe
    
    - uses: actions/upload-artifact@v2
      with: 
        name: lin
        path: lin.exe

